version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201710-02
    working_directory: /home/circleci/regtests
    steps:
      - checkout:
          path: /home/circleci/regtests
      - run:
          name: Change to Python 3.6 and install python dependencies
          command: |
            curl -fsSLO https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
            bash Miniconda3-latest-Linux-x86_64.sh -b -p ~/conda
            rm Miniconda3-latest-Linux-x86_64.sh
            echo "export PATH=~/conda/bin:$PATH" >> ~/.bashrc
            source ~/.bashrc
            conda config --system --prepend channels conda-forge
            conda update -n base -yq conda
            conda update -yq --all
            pip install --no-cache-dir -e /home/circleci/regtests[dev]

      - run:
          name: Run tests
          no_output_timeout: 60m
          command: |
            source ~/.bashrc
            pytest -vs testkraken/tests/test_basic_examples.py testkraken/tests/test_afni.py
      - store_artifacts:
          path: /home/circleci/regtests
